name: Make sure new PRs are sent to development

on:
  push

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'TEST ISSUE MESSAGE'
          pr-message: 'TEST PR MESSAGE'
